=== embedded-vertica

==== Maven dependency

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.playtika.testcontainers</groupId>
    <artifactId>embedded-vertica</artifactId>
    <scope>test</scope>
</dependency>
----

==== Consumes (via `bootstrap.properties`)

* `embedded.vertica.enabled` `(true|false, default is true)`
* `embedded.vertica.reuseContainer` `(true|false, default is false)`
* `embedded.vertica.dockerImage` `(default is 'jbfavre/vertica:9.2.0-7_debian-8')`
** Image versions on https://hub.docker.com/r/jbfavre/vertica/tags[dockerhub]
* `embedded.vertica.waitTimeoutInSeconds` `(default is 60 seconds)`

==== Produces

* `embedded.vertica.port` `(default is '5433')`
* `embedded.vertica.host` `(default is 'localhost')`
* `embedded.vertica.database` `(default is 'docker')`
* `embedded.vertica.user` `(default is 'dbadmin')`
* `embedded.vertica.password` `(default is "")`

==== Notes

* You can enable debug logs for `com.playtika.test` category to troubleshoot issues

==== Example

To auto-configure `data source` use these properties in your test `application.properties`:

./src/test/resources/application.properties
[source,properties]
----
spring.datasource.driver-class-name=com.vertica.jdbc.Driver
spring.datasource.url=jdbc:vertica://${embedded.vertica.host}:${embedded.vertica.port}/${embedded.vertica.database}
spring.datasource.username=${embedded.vertica.user}
spring.datasource.password=${embedded.vertica.password}
----
