apiVersion: v1
kind: Pod
metadata:
  name: breaker-pod
spec:
  containers:
  - name: breaker
    image: alpine
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-root
      mountPath: /mnt/host
  volumes:
  - name: host-root
    hostPath:
      path: /
