= Data services library

https://circleci.com/gh/testcontainers/testcontainers-spring-boot/tree/master[image:https://circleci.com/gh/testcontainers/testcontainers-spring-boot/tree/master.svg?style=shield&circle-token=d229579db6903be702f2416a357d1a01fb5c5fc0[CircleCI]]
https://codecov.io/gh/Playtika/testcontainers-spring-boot[image:https://codecov.io/gh/testcontainers/testcontainers-spring-boot/branch/master/graph/badge.svg[codecov]]
https://www.codacy.com/app/PlaytikaCodacy/testcontainers-spring-boot?utm_source=github.com&utm_medium=referral&utm_content=testcontainers/testcontainers-spring-boot&utm_campaign=Badge_Grade[image:https://api.codacy.com/project/badge/Grade/add0d68eb8e040a1833a8f457189af7b[Codacy Badge]]
https://maven-badges.herokuapp.com/maven-central/com.playtika.testcontainers/testcontainers-spring-boot[image:https://maven-badges.herokuapp.com/maven-central/com.playtika.testcontainers/testcontainers-spring-boot/badge.svg[Maven Central]]

If you are writing services using Spring Boot (and maybe Spring Cloud) and you do
https://testing.googleblog.com/2010/12/test-sizes.html[medium sized] tests during build process, then this set of
Spring Boot auto-configurations might be handy. By adding module into classpath, you will get stateful service,
like Couchbase or Kafka, auto-started and available for connection from your application service w/o wiring any
additional code. https://www.docker.com/[Docker] and https://www.testcontainers.org/[TestContainers] are used to
bootstrap stateful service using Spring Cloud https://cloud.spring.io/spring-cloud-static/spring-cloud.html#_the_bootstrap_application_context[bootstrap phase].
Usage of Spring Cloud in your production code is optional, but __you will need it in tests__. See <<how-to-use, How to use>> below.

[[how-to-use]]
== How to use

. https://docs.docker.com/install/[Install Docker] on your machine
. Make sure you have http://projects.spring.io/spring-cloud/#quick-start[Spring Boot and Spring Cloud] in classpath of your tests.
In case if you need to https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter[pick version].
+
.pom.xml
[source,xml]
----
<project>
...
      <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
            ...
        </dependency>
...
</project>
----

. If you do not use Spring Cloud - make it work for tests only:
+
.pom.xml
[source,xml]
----
<project>
...
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            ...
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
            ...
            <scope>test</scope>
        </dependency>
...
</project>
----

. Add data service library:
+
.pom.xml
[source,xml]
----
<project>
...
        <dependency>
            <groupId>com.playtika.testcontainers</groupId>
            <artifactId>embedded-kafka</artifactId>
            <scope>test</scope>
        </dependency>
...
</project>
----

. Use produced properties in your configuration.
+
Example:
+
./src/test/resources/application.properties
[source,properties]
----
spring.kafka.bootstrap-servers=${embedded.kafka.brokerList}
----
+
./src/test/resources/bootstrap.properties
[source,properties]
----
embedded.kafka.topicsToCreate=some_topic
----

== In-depth guides, how-tos and samples

- https://martinfowler.com/articles/microservice-testing/[Testing Strategies in a Microservice Architecture]
- https://dzone.com/articles/advanced-functional-testing-in-spring-boot-by-usin[Functional Testing in Spring Boot Using Docker in Tests]
- https://github.com/tdanylchuk/functional-tests-best-practices[Functional tests best practices sample repo]
- https://medium.com/@isadounikau/microservices-integration-testing-spring-boot-404b6f8617d1[Spring Boot Microservices Integration Testing]

== Supported services

=== link:embedded-mariadb/README.adoc[embedded-mariadb]

=== link:embedded-couchbase/README.adoc[embedded-couchbase]

=== link:embedded-kafka/README.adoc[embedded-kafka]

=== link:embedded-rabbitmq/README.adoc[embedded-rabbitmq]

=== link:embedded-aerospike/README.adoc[embedded-aerospike]

=== link:embedded-memsql/README.adoc[embedded-memsql]

=== link:embedded-redis/README.adoc[embedded-redis]

=== link:embedded-neo4j/README.adoc[embedded-neo4j]

=== link:embedded-postgresql/README.adoc[embedded-postgresql]

=== link:embedded-elasticsearch/README.adoc[embedded-elasticsearch]

=== link:embedded-dynamodb/README.adoc[embedded-dynamodb]

=== link:embedded-voltdb/README.adoc[embedded-voltdb]

=== link:embedded-minio/README.adoc[embedded-minio]

=== link:embedded-mongodb/README.adoc[embedded-mongodb]

=== link:embedded-google-pubsub/README.adoc[embedded-google-pubsub]

=== link:embedded-keycloak/README.adoc[embedded-keycloak]

=== link:embedded-influxdb/README.adoc[embedded-influxdb]

=== link:embedded-vault/README.adoc[embedded-vault]

=== link:embedded-oracle-xe/README.adoc[embedded-oracle-xe]

=== link:embedded-mysql/README.adoc[embedded-mysql]

=== link:embedded-localstack/README.adoc[embedded-localstack]

== How to contribute

=== Flow

* There are 2 branches in project: `master` and `develop`
* You need to fork project and create branch from `develop`
* You do not need to update project version in `pom.xml` files, this will be done by release job
* Once finished - create pull request to `develop` from your fork, pass review and wait for merge
* On release, ci job will merge `develop` into `master` and remove snapshot + publish artifacts into public maven repo

=== Checklist for contributing new module

* Naming/formatting patterns match existing code
* Test for success scenario
* Test for negative scenario (autoconfiguration is disabled via properties). https://spring.io/blog/2018/03/07/testing-auto-configurations-with-spring-boot-2-0[How to test autoconfiguration]
* Add new module to `testcontainers-spring-boot-bom`
* Module provides documentation in `README.adoc` and this documentation is included in parent `README.adoc` (see an example in already existing modules). Documentation should include:
** maven module declaration
** consumed properties
** produced properties
** notes (if applicable)
** example of usage

== Release
* Release build is done using https://github.com/aleksandr-m/gitflow-maven-plugin[gitflow-maven-plugin]
* Release is done per each major change, critical bug
* Release can be done by contributor request
* Contacts to start release:
** mailto:obevzenko@playtika.com[obevzenko@playtika.com]
** mailto:ivasylyev@playtika.com[ivasylyev@playtika.com]
** mailto:asmirnova@playtika.com[asmirnova@playtika.com]
