=== embedded-artifactory

==== Maven dependency

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.playtika.testcontainers</groupId>
    <artifactId>embedded-artifactory</artifactId>
    <scope>test</scope>
</dependency>
----

==== Consumes (via `bootstrap.properties`)

* `embedded.artifactory.enabled` `(true|false, default is true)`
* `embedded.artifactory.reuseContainer` `(true|false, default is false)`
* `embedded.artifactory.dockerImage` `(default is 'releases-docker.jfrog.io/jfrog/artifactory-oss:7.98.9')`
** Release notes on https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes[jfrog.com]
* `embedded.artifactory.networkAlias` `(default is 'artifactory')`
* `embedded.artifactory.username` `(default is 'admin')`
* `embedded.artifactory.password` `(default is 'password')`
* `embedded.toxiproxy.proxies.artifactory.enabled` Enables both creation of the container with ToxiProxy TCP proxy and a proxy to the `embedded-artifactory` container.

==== PostgreSQL backing store

Artifactory uses PostgreSQL as its backing database, provided by the `embedded-postgresql` module.
Configure the database via `embedded.postgresql.*` properties:

* `embedded.postgresql.user` `(default is 'postgresql')`
* `embedded.postgresql.password` `(default is 'letmein')`
* `embedded.postgresql.database` `(default is 'test_db')`
* `embedded.postgresql.networkAlias` `(default is 'postgresql.testcontainer.docker')`
* `embedded.postgresql.dockerImage` `(default is 'postgres:18-alpine')`

Example override in `bootstrap.properties`:
[source,properties]
----
embedded.postgresql.user=artifactory
embedded.postgresql.password=artifactory
embedded.postgresql.database=artifactory
----

==== Produces

* `embedded.artifactory.host`
* `embedded.artifactory.port`
* `embedded.artifactory.username`
* `embedded.artifactory.password`
* `embedded.artifactory.toxiproxy.host`
* `embedded.artifactory.toxiproxy.port`
* `embedded.artifactory.staticNetworkAlias`
* `embedded.artifactory.internalRestApiPort`
* `embedded.artifactory.internalGeneralPort`
* Bean `ToxiproxyClientProxy artifactoryContainerProxy`
