
storage:
  dbPath: /data/db

processManagement:
  timeZoneInfo: /usr/share/zoneinfo

net:
  port: 27017
  bindIp: 0.0.0.0

security:
  keyFile: /data/configdb/mongod.keyfile
  authorization: enabled

replication:
  replSetName: ${replica-set-name}