=== embedded-mongodb

==== Maven dependency

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.playtika.testcontainers</groupId>
    <artifactId>embedded-mongodb</artifactId>
    <scope>test</scope>
</dependency>
----

==== Consumes (via `bootstrap.properties`)

* `embedded.mongodb.enabled` `(true|false, default is true)`
* `embedded.mongodb.reuseContainer` `(true|false, default is false)`
* `embedded.mongodb.dockerImage` `(default is 'mongodb/mongodb-community-server:8.3.7-ubuntu2204')`
** Image versions on https://hub.docker.com/_/mongo?tab=tags[dockerhub]
* `embedded.mongodb.host` `(default is localhost)`
* `embedded.mongodb.port` `(default is 27017)`
* `embedded.mongodb.username`
* `embedded.mongodb.password`
* `embedded.mongodb.database` `(default is test)`
* `embedded.mongodb.replica-set-name` Default is to run in standalone
* `embedded.toxiproxy.proxies.mongodb.enabled` Enables both creation of the container with ToxiProxy TCP proxy and a proxy to the `embedded-mongodb` container.


==== Produces

* `embedded.mongodb.host`
* `embedded.mongodb.port`
* `embedded.mongodb.username`
* `embedded.mongodb.password`
* `embedded.mongodb.database`
* `embedded.mongodb.replica-set-name`
* `embedded.mongodb.toxiproxy.host`
* `embedded.mongodb.toxiproxy.port`
* `embedded.mongodb.networkAlias`
* `embedded.mongodb.internalPort`
* Bean `ToxiproxyClientProxy mongodbContainerProxy`

==== Example

To auto-configure `spring-data-mongodb` use these properties in your test `application.properties`:

./src/test/resources/application.properties
[source,properties]
----
spring.mongodb.uri=mongodb://${embedded.mongodb.host}:${embedded.mongodb.port}/${embedded.mongodb.database}
----

For replicaset, add additional mongodb properties: `?replicaSet=${embedded.mongodb.replica-set-name}&directConnection=true&authSource=admin`
