=== embedded-azurite

==== Maven dependency

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.playtika.testcontainers</groupId>
    <artifactId>embedded-azurite</artifactId>
    <scope>test</scope>
</dependency>
----

==== Consumes (via `bootstrap.properties`)
* `embedded.azurite.enabled` `(true|false, default is true)`
* `embedded.azurite.reuseContainer` `(true|false, default is false)`
* `embedded.azurite.dockerImage` `(default is 'mcr.microsoft.com/azure-storage/azurite')`
** Image versions on https://hub.docker.com/_/microsoft-azure-storage-azurite
* `embedded.azurite.port` `(default is 10000)`
* `embedded.toxiproxy.proxies.azurite.enabled` Enables both creation of the container with ToxiProxy TCP proxy and a proxy to the `embedded-azurite` container.


Account name and account key are hardcoded as of https://github.com/Azure/Azurite#default-storage-account.

==== Produces

* `embedded.azurite.host`
* `embedded.azurite.port`
* `embedded.azurite.account-name`
* `embedded.azurite.account-key`
* `embedded.azurite.blob-endpoint` (computed property `http://${host}:${port}/${accountName}` for convient configuration with `spring-cloud-azure-starter-storage-blob`)
* `embedded.azurite.toxiproxy.host`
* `embedded.azurite.toxiproxy.port`
* Bean `ToxiproxyContainer.ContainerProxy azuriteContainerProxy`
==== Example

Use `com.azure.spring:spring-cloud-azure-starter-storage-blob` (see https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage)
and configure your application context as follows:

[source,yaml]
./src/test/resources/application.yaml
----
spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${embedded.azurite.account-name}
          account-key: ${embedded.azurite.account-key}
          endpoint: ${embedded.azurite.blob-endpoint}
----

You can then access all beans from `spring-cloud-azure-starter-storage-blob`, i.e. `BlobServiceClientBuilder`.
