=== embedded-selenium

==== Maven dependency

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.playtika.testcontainers</groupId>
    <artifactId>embedded-selenium</artifactId>
    <scope>test</scope>
</dependency>
----

==== Consumes (via `bootstrap.properties`)

* `embedded.selenium.enabled` `(true|false, default is true)`
* `embedded.selenium.docker-image` `(Docker image, e.g. "selenium/standalone-chrome:4.x.x")`
** Available images on https://hub.docker.com/u/selenium[Docker Hub]
** Use `selenium/standalone-chrome`, `selenium/standalone-firefox`, or `selenium/standalone-edge`
* `embedded.selenium.arguments` `(list of browser arguments passed to ChromeOptions/FirefoxOptions)`
* `embedded.selenium.vnc.mode` `RECORD_ALL | SKIP | RECORD_FAILING`
* `embedded.selenium.vnc.recording-dir` `a file location`
* `embedded.toxiproxy.proxies.selenium.enabled` Enables both creation of the container with ToxiProxy TCP proxy and a proxy to the `embedded-selenium` container.


==== Produces

* `embedded.selenium.port`
* `embedded.selenium.host`
* `embedded.selenium.vnc.host`
* `embedded.selenium.vnc.port`
* `embedded.selenium.vnc.username`
* `embedded.selenium.vnc.password`
* `embedded.selenium.toxiproxy.host`
* `embedded.selenium.toxiproxy.port`
* `embedded.selenium.networkAlias`
* Bean `ToxiproxyClientProxy seleniumContainerProxy`

==== Browser selection

The browser is determined by the Docker image, not by capabilities.
Use the appropriate standalone image for the browser you need:

[cols="1,2"]
|===
|Browser |Image

|Chrome
|`selenium/standalone-chrome:4.x.x`

|Firefox
|`selenium/standalone-firefox:4.x.x`

|Edge
|`selenium/standalone-edge:4.x.x`
|===

==== Usage

The container exposes a standard Selenium WebDriver endpoint. Create a `RemoteWebDriver` using the container's address and pass browser options at session creation time:

[source,java]
----
@Autowired
private BrowserWebDriverContainer container;

@Test
void test() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");

    RemoteWebDriver driver = new RemoteWebDriver(container.getSeleniumAddress(), options);
    driver.get("http://" + dockerHostname + ":" + port);
    assertThat(driver.getTitle()).isEqualTo("Hello World");
}
----

Browser arguments from `embedded.selenium.arguments` are pre-applied via the auto-configured `ChromeOptions` or `FirefoxOptions` bean. You can override or extend it with a `@TestConfiguration`:

[source,java]
----
@TestConfiguration
static class TestConfig {

    @Bean
    public ChromeOptions chromeOptions(SeleniumProperties properties) {
        ChromeOptions options = new ChromeOptions();
        properties.apply(options);
        options.addArguments("--disable-gpu");
        return options;
    }
}
----

To get the Docker host address (e.g. to reach your Spring Boot app from inside the container):

[source,java]
----
@DockerHostname
private String dockerHostname;
----

Full example:

[source,java]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class MySeleniumTest {

    @Autowired
    private BrowserWebDriverContainer container;

    @LocalServerPort
    private int port;

    @DockerHostname
    private String dockerHostname;

    @Test
    void pageLoads() {
        RemoteWebDriver driver = new RemoteWebDriver(
            container.getSeleniumAddress(), new ChromeOptions());
        driver.get("http://" + dockerHostname + ":" + port + "/index.html");
        assertThat(driver.getTitle()).isEqualTo("My App");
    }
}
----
