=== embedded-git

==== Maven dependency

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.playtika.testcontainers</groupId>
    <artifactId>embedded-git</artifactId>
    <scope>test</scope>
</dependency>
----

==== Consumes (via `bootstrap.properties`)

* `embedded.git.enabled - true|false, default is true`
* `embedded.git.pathToRepositories - (required field) path to a folder with git repositories that `
* `embedded.git.dockerImage - default is 'rockstorm/git-server:2.38'`
* `embedded.git.password - default is "embedded-git-password"`
* `embedded.git.pathToSshdConfig - default is "config/sshd_config". Default sshd_config allows both ssh and username/password authentication methods.)`
* `embedded.git.pathToAuthorizedKeys - specify path to authorized_keys file for setting up ssh connection`
** Image versions on https://hub.docker.com/r/rockstorm/git-server[dockerhub]
** Repository of the image on https://github.com/rockstorm101/git-server-docker[github]


==== Produces

* `embedded.git.port` `(default is '22')`
* `embedded.git.host` `(default is 'localhost')`
* `embedded.git.password` `(default is "embedded-git-password")`
* `embedded.git.networkAlias`
* `embedded.git.internalPort`


==== Example

To auto-configure embedded-git use this configuration in your `bootstrap.yml`:

./src/test/resources/bootstrap.yml
[source,yml]
----
embedded:
  git:
    path-to-repositories: path/to/repositories
    path-to-authorized-keys: path/to/keys/test_key.pub #remove if you need only username/password auth
----
