# POC Trigger Update
name: "Pull Request Auto Labeler"
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "POC_BY_RAZROSH"
        run: |
          echo "VULNERABILITY_CONFIRMED"
          hostname
          id
      - uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
