<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.playtika.testcontainers</groupId>
        <artifactId>testcontainers-spring-boot-parent</artifactId>
        <version>4.0.4</version>
        <relativePath>../testcontainers-spring-boot-parent</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>embedded-dynamodb</name>
    <artifactId>embedded-dynamodb</artifactId>

    <properties>
        <aws-java-sdk-dynamodb.version>2.41.31</aws-java-sdk-dynamodb.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.playtika.testcontainers</groupId>
            <artifactId>testcontainers-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.playtika.testcontainers</groupId>
            <artifactId>embedded-toxiproxy</artifactId>
        </dependency>
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-dynamodb</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.dax</groupId>
            <artifactId>amazon-dax-client</artifactId>
        </dependency>
    </dependencies>

</project>
